# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """\
[╭╴](cyan)$env_var\
$all[╰─](cyan)$character"""
# 
# Change the default prompt characters
[character]
success_symbol = "[](cyan)"
error_symbol = "[](red)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "bold white"
style_root = "bold white"
format = "[](bold white)[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[](bold yellow)[$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 8
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
truncation_length = 8
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳 "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[kubernetes]
format = ' [ﴱ $context\($namespace\)](bold purple) '
disabled = false

# (deactivated because of no space left)
# 
[terraform]
format = " [ terraform $version]($style) 壟 [$workspace]($style) "
disabled = true

[vagrant]
format = " [ vagrant $version]($style) "
disabled = true

[docker_context]
format = " [ $context](bold blue) "
disabled = true

[helm]
format = " [ $version](bold purple) "
disabled = true

[python]
symbol = " "
python_binary = "python3"
disabled = true

[nodejs]
format = " [ $version](bold green) "
disabled = true

[ruby]
format = " [ $version]($style) "
disabled = true